function  runmex(  )
%RUNMEX Summary of this function goes here
%   Detailed explanation goes here
opt = {['-I.']};

sources = {'romeo.cpp', ...
    'algorithm.cpp', ...
    'k_rem_pio2.cpp', ...
    'unwrapping.cpp', ...
    'weights.cpp', ...
    'e_rem_pio2.cpp', ...
    'rem2pi.cpp', ...
    'seed.cpp', ...
    'utility.cpp' };

% mex('-v',opt{:},sources{:})
mex(opt{:},sources{:})

end

