% Load Field(s)
[iField1,voxel_size,matrix_size,CF,delta_TE,TE,B0_dir,files]=Read_DICOM('acq1');
[iField2,voxel_size,matrix_size,CF,delta_TE,TE,B0_dir,files]=Read_DICOM('acq2');
[iField3,voxel_size,matrix_size,CF,delta_TE,TE,B0_dir,files]=Read_DICOM('acq3');
[iField4,voxel_size,matrix_size,CF,delta_TE,TE,B0_dir,files]=Read_DICOM('acq4');
% Average
iField = (1/4)*iField1+(1/4)*iField2+(1/4)*iField3+(1/4)*iField4;
% Magnitude
iMag = squeeze(sqrt(sum(abs(iField).^2,4)));
% Mask
Mask = imfill(iMag > 200,'holes');
% Estimate noise and normalize field
if (~exist('noise_level','var'))
     noise_level = calfieldnoise(iField, Mask);
end
iField = iField/noise_level;
% Monopolar acquisitions
[iFreq_raw,N_std] = Fit_ppm_complex(iField);
% Unwrap phase using ROMEO
iFreq = romeo(iFreq_raw, iMag, single(Mask));
% Background field removal
[RDF,shim] = PDF(iFreq,N_std,Mask,matrix_size,voxel_size,B0_dir,0,100);
% R2*
R2s = arlo(TE,abs(iField));
% Estimate a uniform region for regularization
c = matrix_size(3)/2;
% Threshold parameter, user specified
t = 33;
Mask_CSF = Mask.*(Mask(:,:,c)-imdilate(imerode(imfill((R2s(:,:,c)>t).*Mask(:,:,c),'holes'),strel('sphere',5)),strel('sphere',20)));
% Save local field generated by PDF
save RDF.mat RDF iFreq iFreq_raw iMag N_std Mask matrix_size...
     voxel_size delta_TE CF B0_dir Mask_CSF R2s;
% QSM
QSM = MEDI_L1('filename', 'RDF.mat', 'lambda', 1000, 'merit', 'msmv', 5);
