function make_schematic(slice)

% Use SNR = 500 for schematic
load('schematic_snr_500.mat')

% Make image arrays
imwrite(uint8(255.*apply_wl([abs(RDF(:,:,slice))-fMask(:,:,slice)...
    abs(RDF_s0(:,:,slice))-fMask(:,:,slice)...
    abs(RDF_s(:,:,slice))-fMask(:,:,slice)...
    QSMs{9}(:,:,slice)-fMask(:,:,slice)],0.5,0)),'fields_schematic.tiff')

imwrite(uint8(255.*apply_wl([Mask(:,:,slice)-~Mask(:,:,slice)*0.1...
    Me(:,:,slice)-~Me(:,:,slice)*0.1...
    (Mask(:,:,slice)-Me(:,:,slice))-~(Mask(:,:,slice)-Me(:,:,slice))*0.1...
    (imbinarize(abs(Me(:,:,slice).*RDF_s0(:,:,slice)),t) == 1)-~(imbinarize(abs(Me(:,:,slice).*RDF_s0(:,:,slice)),t) == 1).*0.1],0.5,0)),...
    'mask_schematic.tiff')