% Run simulation
%
% Creates simulation data for comparison of mSMV to ground truth
% and other shadow reduction methods
%
% Alexandra G. Roberts
% MRI Lab
% Cornell University
% 03/31/2022

clear

% Load data
load xS;
R2s = load('R2s_xS_sim.mat').R2s_xS_sim; 
true_QSM = xS(:,:,:,6);
matrix_size = size(true_QSM);
gray_mask = abs(true_QSM-0.05)<0.0001;

% Add background field
background_field = 1;
x_bk_ppm = 9.4;
x_gt = true_QSM;
if background_field == 1
    x = x_gt + ~Mask.*x_bk_ppm;
    filename = 'data\simulation\RDF_sim.mat';
else
    x = x_gt;
    filename = 'data\simulation\RDF_sim_gt.mat';
end

% Simulation parameters
SNR = 500;
delta_TE = 2.6e-3;
B0_dir = [ 0 0 1];  
matrix_size = [size(true_QSM,1) size(true_QSM,2) size(true_QSM,3)];
voxel_size = [.9375 .9375 1.5];
CF = 127e6;
numecho = 11;
TE = [1:numecho]*delta_TE;

% Create field with additive complex Gaussian noise

D = dipole_kernel(matrix_size,voxel_size,B0_dir,'kspace');
B_total = fftn(x).*D;
b_total = ifftn(B_total);
f = b_total.*(CF*1e-6);
mag = (sum(abs(xS),4)/3)+1;
mag = mag/max(mag(:)).*Mask;
for j = 1:numecho
    iField(:,:,:,j) = (mag.*exp(-2*pi*1i*f*TE(j)).*exp(-TE(j).*R2s))+...
        ((1./SNR).*randn(matrix_size)+(1./SNR).*1i*randn(matrix_size));
end

% Generate the magnitude image 
iMag = squeeze(sqrt(sum(abs(iField).^2,4)));

% Normalize field
noise_level = 1/SNR;
iField = iField/noise_level;

% Estimate the frequency offset in each of the voxel using complex fitting 
[iFreq_raw,N_std] = Fit_ppm_complex(iField);

% CSF zero-reference
Mask_CSF = extract_CSF(R2s,Mask,voxel_size);

% Unwrap phase using ROMEO
iFreq = romeo(iFreq_raw, iMag, Mask);
%%
% Save local field generated by PDF
[RDF,shim] = PDF(iFreq,N_std,Mask,matrix_size,voxel_size,B0_dir,0,100);
save(strcat(filename,'_field'),'RDF','iFreq','iFreq_raw','iMag','N_std','Mask',...
    'matrix_size','voxel_size', 'delta_TE', 'CF','B0_dir','Mask_CSF','gray_mask','true_QSM','R2s','iField','-v7.3');
%%
% Run additional iterations of PDF for comparison
% [RDF_250,shim_250] = PDF(iFreq,N_std,Mask,matrix_size,voxel_size,B0_dir,0,250);
% [RDF_500,shim_500] = PDF(iFreq,N_std,Mask,matrix_size,voxel_size,B0_dir,0,500);
% [RDF_1000,shim_1000] = PDF(iFreq,N_std,Mask,matrix_size,voxel_size,B0_dir,0,1000);

